
name: Purple Cow Properties

description: Don't follow the herd

avatar: http://purplecowproper.com/images/logo-default.png

contact:
  phone: 0161 839 0735
  email: info@purplecowproperties.co.uk
  twitter: purplecowproper
  facebook: purplecowproperties
  linkedin: purple-cow-properties

url: http://purplecowproper.com/

baseurl: ""

markdown: kramdown

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed