
name: Purple Cow Properties

description: Don't follow the herd

avatar: http://purplecowproper.com/images/logo-default.png

twitter_user: purplecowproper

url: http://purplecowproper.com/

baseurl: ""